name: ci

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ci-${{ runner.os }}-${{ hashFiles('Cargo.lock') }}
      - uses: taiki-e/install-action@07b4745e0c39a41822af610387492e3e53aa222b # v2
        with:
          tool: nextest@0.9.140
      - name: Format
        run: cargo fmt --check
      - name: Clippy
        run: cargo clippy --workspace --all-targets
      - name: Test
        run: cargo nextest run --workspace
      - name: Doc tests
        run: cargo test --workspace --doc
